# Change these first
owner: LuckUVeryX # Your GitHub organization or username, where this repository lives
repo: luckuveryx-upptime # The name of this repository

sites:
  - name: Portfolio
    url: https://luckuveryx.github.io/
  - name: Minions
    url: https://luckuveryx.github.io/minions/
  - name: Spaced
    url: https://luckuveryx.github.io/spaced/
  - name: Star Realms Health Counter
    url: https://luckuveryx.github.io/star_realms_health_counter/
  - name: Glints
    url: https://glints.com/
  - name: Glints Emp
    url: https://employers.glints.com/
  - name: Glints Staging
    url: https://staging.glints.com/
  - name: Glints Staging Emp
    url: https://employers.staging.glints.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /luckuveryx-upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "LuckUVeryX's Upptime Monitor"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
